packages:
  - 'packages/*'
  - 'test/e2e/**'
  - 'test/native'

allowBuilds:
  esbuild: true

peerDependencyRules:
  allowedVersions:
    typescript: '7.1.0-dev.20260815.1'

minimumReleaseAgeExclude:
  - '@0no-co/*'
  - '@gql.tada/*'
  - 'gql.tada'
  - '@typescript/typescript-darwin-arm64@7.1.0-dev.20260815.1'
  - '@typescript/typescript-darwin-x64@7.1.0-dev.20260815.1'
  - '@typescript/typescript-linux-arm64@7.1.0-dev.20260815.1'
  - '@typescript/typescript-linux-arm@7.1.0-dev.20260815.1'
  - '@typescript/typescript-linux-x64@7.1.0-dev.20260815.1'
  - '@typescript/typescript-win32-arm64@7.1.0-dev.20260815.1'
  - '@typescript/typescript-win32-x64@7.1.0-dev.20260815.1'
  - typescript@7.1.0-dev.20260815.1

overrides:
  'typescript@<7': ^5.3.3
  ua-parser-js@<0.7.33: '>=0.7.33'
  postcss@<8.4.31: '>=8.4.31'
  semver@<5.7.2: '>=5.7.2'
  semver@>=6.0.0 <6.3.1: '>=6.3.1'
  vite@>=4.2.0 <4.2.3: '>=4.2.3'
  json5@>=2.0.0 <2.2.2: '>=2.2.2'
  '@babel/traverse@<7.23.2': '>=7.23.2'
