packages:
  - 'packages/*'
  - 'test/e2e/**'

allowBuilds:
  esbuild: true

overrides:
  typescript: ^5.3.3
  ua-parser-js@<0.7.33: '>=0.7.33'
  postcss@<8.4.31: '>=8.4.31'
  semver@<5.7.2: '>=5.7.2'
  semver@>=6.0.0 <6.3.1: '>=6.3.1'
  vite@>=4.2.0 <4.2.3: '>=4.2.3'
  json5@>=2.0.0 <2.2.2: '>=2.2.2'
  '@babel/traverse@<7.23.2': '>=7.23.2'
